### PR TITLE
pixie optimizer

### PR DESCRIPTION
**Pull request by ram-lilbigthings**

### CODE REVIEW

**Comment by ram-lilbigthings** [comment]
Hi, I recently submitted a pull request and I was wondering if you could provide me with an estimate of how long it might take for the pull request to be reviewed and accepted

**Comment by tinify-support** [comment]
Hi there,

Thanks for your submission! We are sorry for the delayed response.

We have detected that there are some issues with the PR:
- As Pixie is a plugin for webflow CMS the platform should be
webflow CMS.
- The submitted URL goes to a login page, rather than an
informational website. Please change the URL to an appropriate landing page.

Have a nice day!

Kind regards,

Pablo Pérez de Ciriza

**Comment by ram-lilbigthings** [comment]
Thanks for letting me know about the problems. I have made the changes both in platform and url. Please check that out and let me know if any other problem is there.

**Comment by PabloPerezDeCiriza** [comment]
Hi again, I just noticed that the line 3 contains a title. Please remove it to match this exact format (https://github.com/tinify/third-party-integrations/blob/master/README.md#requirements). Thank you and sorry for the inconvenience.

**Comment by ram-lilbigthings** [comment]
Removed the title to match the exact format. But please make sure to only write "Pixie" as title and use pixie logo when you add this plugin.

**Comment by PabloPerezDeCiriza** [comment]
I am sorry to tell you that we can not set the name and the logo as "Pixie". We list by type and platform. But you could emphasize that in your description if you like with something like "Supercharge your Webflow CMS with Pixie, an image optimizer powered by TinyPNG. Achieve faster load times and better SEO effortlessly!".

**Comment by ram-lilbigthings** [comment]
Thanks for your suggestion. And I have updated it

**Comment by PabloPerezDeCiriza** [comment]
hi @ram-lilbigthings. Today is not going to be possible to deploy it. I hope we can tomorrow.

**Comment by ram-lilbigthings** [comment]
hi @PabloPerezDeCiriza. Can you deploy it today?

**Comment by PabloPerezDeCiriza** [comment]
Hi again. Today is being a very busy day, and we do not deploy on Fridays, so I am sorry to tell you that we will try on Monday.

**Comment by PabloPerezDeCiriza** [comment]
Done. Have a nice Monday!

**Comment by ram-lilbigthings** [comment]
Hello @PabloPerezDeCiriza, could you please update the text "webflow CMS Plugin" to "Webflow CMS Plugin"?

**Comment by PabloPerezDeCiriza** [comment]
Hello. Sure we will, but never on Friday, sorry.

**Comment by ram-lilbigthings** [comment]
hi @PabloPerezDeCiriza. Can you change it today?

**Comment by ddmicu** [comment]
Hi there,

I've updated the capitalization of the word. This change will be reflected on the website after our next deployment but I can't give you an exact date when this will be.

For any other updates that you want on your plugin, please submit a PR.

**Pull request merged**
