### PR TITLE
Integration with Kentico CMS

### PR DESCRIPTION
**Pull request by diger74**
Blog article: https://diger74.net/image-optimization-using-tinypng-api
Nuget package: https://www.nuget.org/packages/Delete.Kentico12.TinyPng/
Code repository: https://github.com/diger74/Delete.Kentico12.TinyPng

### CODE REVIEW

**Comment by jesperlofgren** [comment]
Would it be possible to provide a logotype for the Kentico CMS?
The format needs to be .svg, preferably around 30kb, in color and square.

**Comment by diger74** [comment]
Can you use one of these branding elements?
https://brand.kentico.com/d/8mGnybcVIQZM/brand-identity

**Comment by diger74** [comment]
Sorry for the late answer. [Here is the svg square icon](https://www.dropbox.com/s/e9n7b3xqwr1lrmx/Kentico_Logotype_shortcut_rgb.svg?dl=0), it's 4 KB.

**Comment by Evertrotshuizen** [comment]
Hi Diger74,

Thanks for the logo! We will add your integration in our next release of the website and let you know when it's live.

**Pull request merged**
