### PR TITLE
Create php-script.md

### PR DESCRIPTION
**Pull request by arcasraak**

### CODE REVIEW

**Comment by rkoopmans** [comment]
Thanks a lot for your submission and writing a blog post on how to use Tinify with PHP. Unfortunately the script is very minimal and is not a plugin for a specific software, nor does it cover a specific use case that is not covered by the regular Tinify PHP client (which includes things like error handling, and more). Due to that it just does not fit between the current list of third party solutions currently present on https://tinypng.com/third-party.

**Comment by arcasraak** [comment]
Hi Remco,

Really sad to hear that, as I have worked hard on the page, specifically
for implementing and perfecting the live preview section.

Thanks for pointing out the insufficiency of the page, though.

Apart from error handling, could you please guide me on what other aspects
you'd like me to cover so I can write about and make it more complete?

I'm really keen to get this page getting somewhere!

**Comment by PabloPerezDeCiriza** [comment]
Hi there, 
Thank you so much for your enthusiasm, we really appreciate it! The key issue here is that, while your page may be incredibly informative, it’s not a solution in itself (a piece of software that addresses a problem), so it doesn’t quite belong on the third-party solutions page. In my view, it would be a great fit for a PHP community instead.

**Comment by arcasraak** [comment]
Hi Pablo,

Thank you for following up, I really appreciate your time!

Honestly, I initially thought I should have been creating a clone of your image compression, so I spent a lot of time coding the script, perfecting the UI, and updating the old page I had created for TinyPNG with the live demo. My mistake :(

Later, I realized that the page should belong to one of the categories you mentioned. So, I tried writing a guide about PHP similar to the "[macOS Automator script](https://danielsetzermann.com/howto/how-to-compress-png-files/)" you've already added to your Third-Party Solutions page. So, these all took several complete days for me.

I don't want to push you to merge the request, but I'm willing to adjust the page in any way you'd like, so my hard work doesn't go to waste.

If you could let me know what more you'd expect from the page, I'd appreciate it! I can update it to meet your expectations.

Thanks a lot!

**Comment by PabloPerezDeCiriza** [comment]
Hi again! I'm very sorry to disappoint you, but the script you are referring to was linked 6 years ago and explained how to use a tool that, at that time, was probably hard to use without the guide.

**If you could let me know what more you'd expect from the page, I'd appreciate it!**
We expect a solution, meaning a plugin, an app, or something that solves a specific problem that our current code doesn't address.

**I'd appreciate it! I can update it to meet your expectations.**
You can't update it to meet our expectations because the core of your pull request does not solve a problem that isn't already addressed by us.

That said, thank you very much for your interest. In my opinion, your page could be very helpful in a PHP forum or community.

**Pull request closed without merging**
