### PR TITLE
Update cli-binary-linux-windows.md

### PR DESCRIPTION
**Pull request by tarampampam**

### CODE REVIEW

**Comment by tarampampam** [comment]
ping @emielvanlankveld

**Comment by edwinw6** [comment]
Thanks for your contribution!

Since your add-on has a CLI it needs to be part of Development collection. Desktop apps really need to have a GUI. As for the platform, please limit it to 1 or 2 platforms (icons), simply because the interface does not allow more than that. I'd suggest keeping the Shell platform icon.

If you still wish to rename your CLI add-on, please update your PR. Otherwise I'll close it.

**Comment by tarampampam** [comment]
Collection changed back to `Development` 3f5c57bfc0b62d910c1e51251db0eb08deb3806c

**Comment by edwinw6** [comment]
Thanks!

**Pull request merged**
